name: flutdot_camera
description: "The flut.Camera project."

publish_to: 'none'

version: 1.0.1+2

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter

  camera: 0.11.0+2
  video_player: 2.9.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: false
  